#!/bin/bash

sudo timedatectl set-timezone Asia/Kolkata
alias update='sudo apt update -y && sudo apt full-upgrade -y && sudo apt autoremove -y && sudo apt clean -y && sudo apt autoclean -y'
git config --global user.name "jrchintu"
git config --global user.email "harrypetersun@outlook.com.com"
export TZ='Asia/Kolkata'

#alias
alias gdup='gdrive upload -p 0AB4ISlC3RuroUk9PVA '
alias update='sudo apt update -y && sudo apt full-upgrade -y && sudo apt autoremove -y && sudo apt clean -y && sudo apt autoclean -y'
alias src='source ~/.bashrc'
alias nb='nano ~/.bashrc'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias g=git
alias ga='git add'
alias gdb='git push -d origin '
alias gaa='git add --all'
alias gb='git branch'
alias gbD='git branch -D'
alias gbd='git branch -d'
alias gba='git branch -a'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gd='git diff'
alias gcl='git clone --recurse-submodules'
alias gds='git diff --staged'
alias gf='git fetch'
alias gl='git pull'
alias glo='git log --oneline --decorate'
alias glog='git log --oneline --decorate --graph'
alias gloga='git log --oneline --decorate --graph --all'
alias glol='git log --graph --pretty='\''%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'
alias gm='git merge'
alias gma='git merge --abort'
alias gp='git push'
alias gpsup='git push --set-upstream origin $(git_current_branch)'
alias gr='git remote'
alias gra='git remote add'
alias grv='git remote -v'
alias grb='git rebase'
alias grba='git rebase --abort'
alias grbc='git rebase --continue'
alias grbi='git rebase -i'
alias grbs='git rebase --skip'
alias grev='git revert'
alias grh='git reset'
alias grm='git rm'
alias grrm='git remote remove'
alias gsh='git show'
alias l='la'
alias md='mkdir -p'
alias rd='rmdir -p'
alias gcp='gpick'
alias gpc='gpick'
alias c='clear'
alias n='nano'
alias tx='tmux'
alias t='tmux attach -t0'
alias t1='tmux attach -t1'
alias tl='tmux ls'
alias h='htop'
alias cc='ccache -s'
alias s='source'
alias q='exit'
alias e='echo'
alias du='du -h'
alias dus='du -sh'
alias d='df -h'
alias wh='which'
alias rmrf='rm -rf'
alias myip="curl http://ipecho.net/plain; echo"
alias speed='curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -'
alias rs='repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j'
alias f='free -h'
alias sshn='ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
alias gssh='gcloud cloud-shell ssh'

